language: node_js
node_js:
  - "5.9"
env:
  global:
    - CXX=g++-4.8
    - GH_REF: github.com/user378230/ui-select
    - secure: "PkIhXXwrR5fHh7fH+2WizaY0MmK1l1Dr7PCqs112PkEimVPcntRJeA5pjTwGRwHm+RSkFVtfo38EY/GUwzhLSRTO7WZ+id+vIMGQLgiofqrOwi0nq93esG6qI8Jg5K0GUt8mzg5m9B2tgm2I91RAojEhIukKcbsDsq3hNAUy71Y="
# user378230
#   - secure: "cjFEwojCr8KpwqUUw5vDlDTClTw/IMOueMOTM31uQxTCi8KMwrpeHcOXBcObHlJmcBUJNcKBwp8wZyYadcO9AH/DuMOUwrxQTiU6ejjDmMK9MMO6wpvDvsKNwptNw5TCucO7w4Ukw6lkMMO4wqzDpVPDjm4vJ8OSwpLDhsKBIsKtwoliUnBVKAjDkjPCuMKyw4vDmVQ3w57Dhg/DsSLChsKQwrvDjGfDhXcUAVTDpsKzwoMZBU3DgMKUwq8kwqt9VgV0ZcOmw6LChMOsG8K6HRHCpDDCj8Ogwo83w6TCtRLCjgvCosKtdcOYw7fDmsOMwr4pwrzCpcOCL1cETDNyw5jCpj9kw4xKwoM0WsKTNcKZTgA/w47Cm8Kec1TDncOkw4NrdcO5w5RGDMKlCBbDpVLDt8Odw5/CqxjCoy55O2PCmi0Tw4Z3wo3Cm8O2w6JRSFDDmAZEFcKew7HDoyJhw7PChcKPO0gyPXkPw4vClsKSXydeR8KmRVzDqcKfNXfCnzwow4EPbmYtw4nDsF3DoHbCvVzDh8K+wp0mw7IXJUsEwr5twoLDnU/CrGMrwq4uwrTCvgHDkDsCcHJCb8KJSwMGI1BrMsOhwoV/G0RSG8Kxw4nCrMKBw6LDusOOw697PMKhLmbCr8OQwrLCi1PDvMObQMOAw79HRMOLw4/DpMKjORbCqCfCuMKUNRzCssOZE8OVw7vCoMK2wogOFsK4wqnDlsKOa8KGf3gqfcOSwo3DoRYaCj4RUcOzwrJew6DDhjPCt8KeUlYCPCtwwrt2w59+w5ZJw5LCosKXw5nCl8OqOMKrFTUUwroewrIpMMKFw6h2wp4OQ8O7wr46wqvDoHVAw65Uw5zDglEaw4MIw5fCpTXDi2VFwqlawrjDvlobQTwaGy7DhsOwwrd0YMO9RsKUwrliUkNBw7krwrnCvsKZNMOww7nDhFnCsD3CiMONfQvDl8KZwpl4QcOxwrLCtcKAw6HDtxZMwonChsKCLMKgw4XCj0vCrsKOw49D"
# angular-ui
    

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install --quiet -g gulp  

script: "gulp docs"

after_success: 
  - "echo ${TRAVIS_SECURE_ENV_VARS}"
  - "echo ${GH_KEY:?Missing key}"
  - "bash ./deploy-docs.sh"    

# after_success:
#  - "gulp docs"

#deploy:
#  skip_cleanup: true

#  script: "bash ./deploy-docs.sh"
#  on:
#    all_branches: true
#  on:
#    tags: true

sudo: false

git:
  depth: 10
